### ISSUE TITLE
ID 관련 의견제시

### ISSUE THREAD

**Issue by JeongWonHA** [JihuYang/2020OSS_team_project_developer#3]
아이디가 여기 저기 나눠져서 입력하는 형태로 구현을 해놓아서 이걸 하나로 합치면 좀 더 좋을거 같다는 생각이 들어요. 예를 들면 처음에 아이디를 입력하면 제품을 등록하던지 후기를 등록하던지 처음 입력했던 아이디로 다 처리가 되도록 구현하면 좋을거같은데 어떻게 생각하세요?

**Comment by JihuYang** [comment]
으음 네! 그러면 처음에 아이디를 한번 입력하면 이후에 입력이 없어도 그 아이디로 제품 등록/후기 등록을 한다는 뜻이죠?? 정원학우님이 저번에 구현하셨던 sign in 함수와 비슷하게 코딩해보면 되겠네요!

**Comment by JihuYang** [comment]
아이디 유무 여부와 회원가입 가능하도록 함수 만들었습니다!
